"""add is_active to users

Revision ID: d36daba678b5
Revises: 7321fe0558b8
Create Date: 2026-08-27 19:58:13.370969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36daba678b5'
down_revision: Union[str, Sequence[str], None] = '7321fe0558b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', 
        sa.Column(
            'is_active', 
            sa.Boolean(), 
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
